services:
  db:
    restart: always
    image: postgres:15.2
    container_name: testtask
    environment:
      POSTGRES_USER: superboy
      POSTGRES_PASSWORD: superboy
      POSTGRES_DB: song-lib-db
    ports:
      - 9900:5432